### ISSUE TITLE
VP8 packet decoding for multiple tracks have performance issues

### ISSUE THREAD

**Issue by SaverioFrancesco** [adalkiran/webrtc-nuts-and-bolts#1]
Hello, and thank you for the amazing project.

I was reading [08-VP8-PACKET-DECODE.md](https://github.com/adalkiran/webrtc-nuts-and-bolts/blob/main/docs/08-VP8-PACKET-DECODE.md) looking for a solution to a vpx limitation.

I have a golang webrtc client (livekit) that connects to a room and receives inbound tracks as many participants are publishing a track in the room. My goal is to decode the vp8 packets and send them to another server (no saving on file required.) Each track is handled in a separate go routine.

It seems that `err := vpx.Error(vpx.CodecDecode(d.context, string(currentFrame), uint32(len(currentFrame)), nil, 0))` dose not perform work in parallel. More precisely I believe this call is mutually exclusive. This is a big problem. I'm interested in sampling each vp8 track 6 times a second. 
I tried skipping some RTP packets but the vpx.CodecDecode breaks.

How would you handle this?

**Comment by adalkiran** [comment]
Hi,

Thanks for your good words on my project. First of all, I didn't use this project in production, because of this, I can speak on probabilities:

- In this project, for each UDP client, RtpDepacketizer and vp8Depacketizer channels are initialized with size of 1. In your code, you can increase this size limit for your packet channels, as follows: https://github.com/adalkiran/webrtc-nuts-and-bolts/blob/f7b756dd2af666807d96016fece226e6545defae/backend/src/agent/udpclientsocket.go#L48

- I don't have deeper experience with Go C Bindings and internals of original libvpx C library, libvpx-go packet may import libvpx C library as one instance per process. Or libvpx C library may have a limitation on processing one call per process. You can search for workarounds for creating libvpx in more than one instance. You can check out for internals: https://github.com/xlab/libvpx-go

- It's unlikely, but because of video encoding and decoding video are compute-intensive tasks, your computer resources could be on their limits.

If you have other questions, ask please.
